import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { readFileSync } from "node:fs";
import { createUser, createDirect, createGroup, type FixtureUser } from "../src/fixtures";
import { connectAs, waitFor, emitWithAck, closeAllSockets, type SocketSession } from "../src/socket";

/**
 * Voice notes end to end: the AUDIO wire contract, the media panel, the
 * sidebar preview, forwarding, token abuse, the upload route's caps (bytes AND
 * the server-enforced 2-minute duration bound), the picked-.ogg path, and the
 * tombstone nulling mediaDurationMs.
 *
 * Fixtures (both generated by ffmpeg, committed):
 *   voice-note.webm      1.2s opus-in-webm (shared with 60-socket-chat)
 *   voice-note.ogg       1.2s opus-in-ogg — sniffs to AUDIO with no voice flag
 *   voice-note-long.webm 150s at 6kbps — over the 2-min bound, under 5MB
 * Regenerate with:
 *   ffmpeg -f lavfi -i "sine=frequency=440:sample_rate=48000" -t 1.2 -c:a libopus -b:a 24k -ac 1 voice-note.ogg
 *   ffmpeg -f lavfi -i "sine=frequency=440:sample_rate=48000" -t 150 -c:a libopus -b:a 6k -ac 1 voice-note-long.webm
 */

/** Hand-copied on purpose, same as 00-contracts and 65-socket-call: the pin
 *  must not import what it pins. */
const MESSAGE_FIELDS = [
  "body",
  "callId",
  "clientMsgId",
  "conversationId",
  "createdAt",
  "deletedAt",
  "editedAt",
  "id",
  "mediaDurationMs",
  "mediaHeight",
  "mediaMime",
  "mediaName",
  "mediaSize",
  "mediaUrl",
  "mediaWidth",
  "replyToId",
  "senderId",
  "type",
];

type WireMessage = Record<string, unknown> & {
  id: string;
  type: string;
  mediaUrl: string | null;
  mediaDurationMs: number | null;
  clientMsgId: string | null;
};

function fixture(name: string): Buffer {
  return readFileSync(new URL(`../fixtures/${name}`, import.meta.url));
}

function voiceForm(conversationId: string, bytes: Buffer, opts: { voice?: boolean; mime?: string } = {}): FormData {
  const form = new FormData();
  form.append("conversationId", conversationId);
  if (opts.voice !== false) form.append("voice", "1");
  // Fresh Uint8Array: Buffer's ArrayBufferLike backing fails Blob's typing.
  form.append("file", new Blob([new Uint8Array(bytes)], { type: opts.mime ?? "audio/webm" }), "Voice message");
  return form;
}

let alice: FixtureUser;
let bob: FixtureUser;
let dmId: string;
let groupId: string;
let aliceSocket: SocketSession;
let bobSocket: SocketSession;
let audioToken: string;
let audioUpload: { mediaUrl: string; mediaDurationMs: number };
let audioMessage: WireMessage;

describe("voice notes", () => {
  afterAll(() => closeAllSockets());

  beforeAll(async () => {
    alice = await createUser("vna");
    bob = await createUser("vnb");
    // Conversations BEFORE sockets: joinInitialRooms only joins existing rooms.
    dmId = await createDirect(alice, bob);
    groupId = await createGroup(alice, [bob], "zz.e2e voice fwd");
    aliceSocket = await connectAs(alice.api);
    bobSocket = await connectAs(bob.api);
  });

  it("an AUDIO message carries the exact 18-field contract on ack, broadcast and REST", async () => {
    const upload = await alice.api.post("/api/upload/chat-media", {
      form: voiceForm(dmId, fixture("voice-note.webm")),
    });
    expect(upload.status).toBe(201);
    expect(upload.body.type).toBe("AUDIO");
    expect(upload.body.mediaDurationMs).toBeGreaterThan(500);
    expect(upload.body.mediaDurationMs).toBeLessThan(3000);
    audioToken = upload.body.mediaToken;
    audioUpload = { mediaUrl: upload.body.mediaUrl, mediaDurationMs: upload.body.mediaDurationMs };

    const clientMsgId = crypto.randomUUID();
    const broadcastPromise = waitFor<{ message: WireMessage }>(
      bobSocket.socket,
      "message:new",
      (p) => p.message?.clientMsgId === clientMsgId,
    );
    const ack = await emitWithAck(aliceSocket.socket, "message:send", {
      conversationId: dmId,
      clientMsgId,
      type: "AUDIO",
      mediaToken: audioToken,
    });
    expect(ack.ok).toBe(true);
    expect(ack.message.type).toBe("AUDIO");
    expect(ack.message.mediaDurationMs).toBe(audioUpload.mediaDurationMs);
    const broadcast = await broadcastPromise;

    const rest = await bob.api.get(`/api/conversations/${dmId}/messages`);
    expect(rest.status).toBe(200);
    const restMessage = rest.body.messages.find((m: WireMessage) => m.clientMsgId === clientMsgId);
    expect(restMessage, "AUDIO message missing from REST history").toBeTruthy();

    expect(Object.keys(ack.message).sort()).toEqual(MESSAGE_FIELDS);
    expect(Object.keys(broadcast.message).sort()).toEqual(MESSAGE_FIELDS);
    expect(Object.keys(restMessage).sort()).toEqual(MESSAGE_FIELDS);
    expect(restMessage).toEqual(ack.message);
    expect(broadcast.message).toEqual(ack.message);
    audioMessage = ack.message as WireMessage;
  });

  it("the media panel lists the AUDIO message", async () => {
    const res = await bob.api.get(`/api/conversations/${dmId}/media`);
    expect(res.status).toBe(200);
    const found = res.body.messages.find((m: WireMessage) => m.id === audioMessage.id);
    expect(found, "AUDIO row missing from the media panel").toBeTruthy();
    expect(found.type).toBe("AUDIO");
  });

  it("the sidebar previews it as 'Voice message'", async () => {
    const res = await alice.api.get("/api/conversations");
    expect(res.status).toBe(200);
    const dm = res.body.conversations.find((c: { id: string }) => c.id === dmId);
    expect(dm, "DM missing from the sidebar").toBeTruthy();
    expect(dm.lastMessage?.preview).toBe("Voice message");
  });

  it("forwarding preserves mediaDurationMs, url and type", async () => {
    const res = await bob.api.post(`/api/conversations/${groupId}/forward`, {
      json: { messageIds: [audioMessage.id] },
    });
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.messages).toHaveLength(1);
    const forwarded = res.body.messages[0];
    expect(forwarded.type).toBe("AUDIO");
    expect(forwarded.mediaUrl).toBe(audioUpload.mediaUrl);
    expect(forwarded.mediaDurationMs).toBe(audioUpload.mediaDurationMs);
    expect(forwarded.senderId).toBe(bob.userId);
    expect(Object.keys(forwarded).sort()).toEqual(MESSAGE_FIELDS);
  });

  it("a tampered AUDIO token is INVALID; a valid one can't be replayed as VIDEO", async () => {
    const tampered = audioToken.slice(0, -1) + (audioToken.endsWith("A") ? "B" : "A");
    const bad = await emitWithAck(aliceSocket.socket, "message:send", {
      conversationId: dmId,
      clientMsgId: crypto.randomUUID(),
      type: "AUDIO",
      mediaToken: tampered,
    });
    expect(bad).toMatchObject({ ok: false, code: "INVALID" });

    // claim.t !== type: an AUDIO token must not mint a VIDEO message.
    const crossType = await emitWithAck(aliceSocket.socket, "message:send", {
      conversationId: dmId,
      clientMsgId: crypto.randomUUID(),
      type: "VIDEO",
      mediaToken: audioToken,
    });
    expect(crossType).toMatchObject({ ok: false, code: "INVALID" });
  });

  it("a >5MB voice upload hits the AUDIO cap, not video's 20MB", async () => {
    // EBML magic + padding: sniffs as webm (video), the voice flag re-types it
    // to audio, so audio's 5MB cap must apply. Rejected before Cloudinary.
    const oversized = Buffer.concat([Buffer.from([0x1a, 0x45, 0xdf, 0xa3]), Buffer.alloc(6 * 1024 * 1024)]);
    const res = await alice.api.post("/api/upload/chat-media", {
      form: voiceForm(dmId, oversized),
    });
    expect(res.status).toBe(413);
    expect(res.body.error).toContain("audio must be 5MB or smaller");
  });

  it("an over-2-minute recording is rejected by the server-side duration bound", async () => {
    // 150s at 6kbps: over the bound, far under the byte cap — only the probed
    // duration can reject it. Pins the server-enforced VOICE_NOTE_MAX_MS.
    const res = await alice.api.post("/api/upload/chat-media", {
      form: voiceForm(dmId, fixture("voice-note-long.webm")),
    });
    expect(res.status).toBe(413);
    expect(res.body.error).toBe("Voice messages can be up to 2 minutes");
  });

  it("a picked .ogg with no voice flag still becomes a bounded AUDIO upload", async () => {
    // OggS is the one container that sniffs to AUDIO on its own — the doc's
    // "recorder-only" is about the composer UI, not the wire. The duration
    // bound applies to this path too (same sniffed-audio check).
    const res = await alice.api.post("/api/upload/chat-media", {
      form: voiceForm(dmId, fixture("voice-note.ogg"), { voice: false, mime: "audio/ogg" }),
    });
    expect(res.status).toBe(201);
    expect(res.body.type).toBe("AUDIO");
    expect(res.body.mediaMime).toBe("audio/ogg");
    expect(res.body.mediaDurationMs).toBeGreaterThan(500);
    expect(res.body.mediaDurationMs).toBeLessThan(3000);
  });

  it("mov, pdf and zip marked voice are all 400", async () => {
    const movHeader = Buffer.concat([
      Buffer.from([0x00, 0x00, 0x00, 0x14]),
      Buffer.from("ftypqt  ", "ascii"),
      Buffer.alloc(64),
    ]);
    const pdfHeader = Buffer.concat([Buffer.from("%PDF-1.4", "ascii"), Buffer.alloc(64)]);
    const zipHeader = Buffer.concat([Buffer.from([0x50, 0x4b, 0x03, 0x04]), Buffer.alloc(64)]);

    for (const bytes of [movHeader, pdfHeader, zipHeader]) {
      const res = await alice.api.post("/api/upload/chat-media", { form: voiceForm(dmId, bytes) });
      expect(res.status).toBe(400);
      expect(res.body.error).toBe("That recording format isn't supported");
    }
  });

  it("delete-for-everyone nulls mediaDurationMs along with the rest of the media", async () => {
    const ack = await emitWithAck(aliceSocket.socket, "message:delete", { messageId: audioMessage.id });
    expect(ack.ok).toBe(true);

    const rest = await bob.api.get(`/api/conversations/${dmId}/messages`);
    const tombstone = rest.body.messages.find((m: WireMessage) => m.id === audioMessage.id);
    expect(tombstone, "tombstone missing from history").toBeTruthy();
    expect(tombstone.deletedAt).toBeTypeOf("string");
    expect(tombstone.mediaUrl).toBeNull();
    expect(tombstone.mediaDurationMs).toBeNull();
  });
});
